export enum AnswerCategory {
    RadioButtons = 1,
    RadioButtons_TextboxLastEntry = 2,
    Checkboxes = 3,
    Checkboxes_TextboxLastEntry = 4,
    Checkboxes_ConditionalTextbox2 = 5,
    Textbox = 6,
    DropDown = 7,
    No_Answer = 8,
    Date_MonthDayYear = 9,
    MatrixRadioButtons = 10,
    MatrixRadioButtons_DropDownLastCol = 11,
    MatrixRadioButtons_TextboxLastRow = 12,
    RadioButtons_in_Matrix_DropDownLastCol = 13,
    Textbox_in_Matrix = 14,
    RadioButons_in_Matrix = 15,
    Calculated = 16,
    Address = 17,
    Immediate_Selection = 18
}
