export enum foca {
    Hi_Lvl_Intro = 1,
    Section_Title = 2,
    PreQ_Intro = 3,
    Lvl_1_Q = 4,
    MatrixRowHea = 5,
    DropDownLabel = 6,
    TxtBoxLabel = 7,
    CalendarLabel1 = 8,
    MonthYearLabel = 9,
    SubQ_TxtBoxLabel = 10,
    Matrix_LastCol_Drop = 11,
    Normal = 12,
    CheckboxLabelRight = 13,
    HugeCharsOnPage = 14,
    Further_Instructions = 15,
    Dummy = 16,
    Picture = 17,
    TxtBoxLabel_w_units = 18
}
