import {Adin} from "../types/database-data/adin";
export var adin:Adin[] = [
    {
        "obj_uid": 100,
        "sort_order": 1,
        "display_condition": null,
        "adin_foca_id": 9,
        "adin_anca_id": 16,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "\"From:\"",
        "txt_legalrep_lang1": "\"From:\"",
        "txt_selfreport_lang1": "\"From:\"",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_from_date",
        "bypass_var": "res_from_date"
    },
    {
        "obj_uid": 200,
        "sort_order": 2,
        "display_condition": null,
        "adin_foca_id": 16,
        "adin_anca_id": 7,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "<!-- From_Month -->",
        "txt_legalrep_lang1": "<!-- From_Month -->",
        "txt_selfreport_lang1": "<!-- From_Month -->",
        "parent_adin_dona_id": 41,
        "legalrep_adin_dona_id": 41,
        "selfreport_adin_dona_id": 41,
        "tracking_key": "res_from_month",
        "bypass_var": "res_from_month"
    },
    {
        "obj_uid": 300,
        "sort_order": 3,
        "display_condition": null,
        "adin_foca_id": 16,
        "adin_anca_id": 7,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "<!-- From_Year -->",
        "txt_legalrep_lang1": "<!-- From_Year -->",
        "txt_selfreport_lang1": "<!-- From_Year -->",
        "parent_adin_dona_id": 42,
        "legalrep_adin_dona_id": 42,
        "selfreport_adin_dona_id": 42,
        "tracking_key": "res_from_year",
        "bypass_var": "res_from_year"
    },
    {
        "obj_uid": 400,
        "sort_order": 4,
        "display_condition": null,
        "adin_foca_id": 9,
        "adin_anca_id": 16,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "\"To:\"",
        "txt_legalrep_lang1": "\"To:\"",
        "txt_selfreport_lang1": "\"To:\"",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_to_date",
        "bypass_var": "res_to_date"
    },
    {
        "obj_uid": 500,
        "sort_order": 5,
        "display_condition": null,
        "adin_foca_id": 16,
        "adin_anca_id": 7,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "<!-- To_Month -->",
        "txt_legalrep_lang1": "<!-- To_Month -->",
        "txt_selfreport_lang1": "<!-- To_Month -->",
        "parent_adin_dona_id": 41,
        "legalrep_adin_dona_id": 41,
        "selfreport_adin_dona_id": 41,
        "tracking_key": "res_to_month",
        "bypass_var": "res_to_month"
    },
    {
        "obj_uid": 600,
        "sort_order": 6,
        "display_condition": null,
        "adin_foca_id": 16,
        "adin_anca_id": 7,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "<!-- To_Year -->",
        "txt_legalrep_lang1": "<!-- To_Year -->",
        "txt_selfreport_lang1": "<!-- To_Year -->",
        "parent_adin_dona_id": 42,
        "legalrep_adin_dona_id": 42,
        "selfreport_adin_dona_id": 42,
        "tracking_key": "res_to_year",
        "bypass_var": "res_to_year"
    },
    {
        "obj_uid": 700,
        "sort_order": 7,
        "display_condition": "check_for_state() == true",
        "adin_foca_id": 4,
        "adin_anca_id": 3,
        "bypass_property": null,
        "txt_parent_lang1": "Select an address you previously entered:",
        "txt_legalrep_lang1": "Select an address you previously entered:",
        "txt_selfreport_lang1": "Select an address you previously entered:",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": null,
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 800,
        "sort_order": 8,
        "display_condition": "check_for_state() == true",
        "adin_foca_id": 6,
        "adin_anca_id": 7,
        "bypass_property": null,
        "txt_parent_lang1": "Select address",
        "txt_legalrep_lang1": "Select address",
        "txt_selfreport_lang1": "Select address",
        "parent_adin_dona_id": 9,
        "legalrep_adin_dona_id": 9,
        "selfreport_adin_dona_id": 9,
        "tracking_key": "res_prev_rep_index",
        "bypass_var": null
    },
    {
        "obj_uid": 900,
        "sort_order": 9,
        "display_condition": "check_for_state() == true",
        "adin_foca_id": 4,
        "adin_anca_id": 8,
        "bypass_property": null,
        "txt_parent_lang1": "OR",
        "txt_legalrep_lang1": "OR",
        "txt_selfreport_lang1": "OR",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": null,
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 1000,
        "sort_order": 10,
        "display_condition": null,
        "adin_foca_id": 7,
        "adin_anca_id": 6,
        "bypass_property": "OPTIONAL",
        "txt_parent_lang1": "Address",
        "txt_legalrep_lang1": "Address",
        "txt_selfreport_lang1": "Address",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_address",
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 1100,
        "sort_order": 11,
        "display_condition": null,
        "adin_foca_id": 7,
        "adin_anca_id": 6,
        "bypass_property": "OPTIONAL",
        "txt_parent_lang1": "Apt/Suite #",
        "txt_legalrep_lang1": "Apt/Suite #",
        "txt_selfreport_lang1": "Apt/Suite #",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_apt",
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 1200,
        "sort_order": 12,
        "display_condition": null,
        "adin_foca_id": 7,
        "adin_anca_id": 6,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "City",
        "txt_legalrep_lang1": "City",
        "txt_selfreport_lang1": "City",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_city",
        "bypass_var": "res_city"
    },
    {
        "obj_uid": 1300,
        "sort_order": 13,
        "display_condition": null,
        "adin_foca_id": 6,
        "adin_anca_id": 7,
        "bypass_property": "REQUIRED",
        "txt_parent_lang1": "State",
        "txt_legalrep_lang1": "State",
        "txt_selfreport_lang1": "State",
        "parent_adin_dona_id": 24,
        "legalrep_adin_dona_id": 24,
        "selfreport_adin_dona_id": 24,
        "tracking_key": "res_state",
        "bypass_var": "res_state"
    },
    {
        "obj_uid": 1400,
        "sort_order": 14,
        "display_condition": null,
        "adin_foca_id": 7,
        "adin_anca_id": 6,
        "bypass_property": "OPTIONAL",
        "txt_parent_lang1": "Zip code",
        "txt_legalrep_lang1": "Zip code",
        "txt_selfreport_lang1": "Zip code",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": "res_zip",
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 1500,
        "sort_order": 15,
        "display_condition": null,
        "adin_foca_id": 4,
        "adin_anca_id": 8,
        "bypass_property": null,
        "txt_parent_lang1": "OR",
        "txt_legalrep_lang1": "OR",
        "txt_selfreport_lang1": "OR",
        "parent_adin_dona_id": null,
        "legalrep_adin_dona_id": null,
        "selfreport_adin_dona_id": null,
        "tracking_key": null,
        "bypass_var": "TRUE"
    },
    {
        "obj_uid": 1600,
        "sort_order": 16,
        "display_condition": null,
        "adin_foca_id": 4,
        "adin_anca_id": 1,
        "bypass_property": "OPTIONAL",
        "txt_parent_lang1": "Select one of these options:",
        "txt_legalrep_lang1": "Select one of these options:",
        "txt_selfreport_lang1": "Select one of these options:",
        "parent_adin_dona_id": 43,
        "legalrep_adin_dona_id": 43,
        "selfreport_adin_dona_id": 43,
        "tracking_key": "res_unsure_foreign",
        "bypass_var": "TRUE"
    }
];