import { Domain } from '../types/database-data/domain';
import { Domains } from '../types/database-data/domains';

export var domain: Domains = {
    1: [
        new Domain(1, 1, 'Less than 12 months'),
        new Domain(2, 2, '12 months'),
        new Domain(3, 3, '13 months'),
        new Domain(4, 4, '14 months'),
        new Domain(5, 5, '15 months'),
        new Domain(6, 6, '16 months'),
        new Domain(7, 7, '17 months'),
        new Domain(8, 8, '18 months'),
        new Domain(9, 9, '19 months'),
        new Domain(10, 10, '20 months'),
        new Domain(11, 11, '21 months'),
        new Domain(12, 12, '22 months'),
        new Domain(13, 13, '23 months'),
        new Domain(14, 14, '2 years'),
        new Domain(15, 15, '3 years'),
        new Domain(16, 16, '4 years'),
        new Domain(17, 17, '5 years'),
        new Domain(18, 18, '6 years'),
        new Domain(19, 19, '7 years'),
        new Domain(20, 20, '8 years'),
        new Domain(21, 21, '9 years'),
        new Domain(22, 22, '10-12 years'),
        new Domain(23, 23, '13-15 years'),
        new Domain(24, 24, '16-17 years'),
        new Domain(25, 25, 'Don\'t know')
    ],
    2: [
        new Domain(1, 1, 'Less than 12 months'),
        new Domain(2, 2, '12 months'),
        new Domain(3, 3, '13 months'),
        new Domain(4, 4, '14 months'),
        new Domain(5, 5, '15 months'),
        new Domain(6, 6, '16 months'),
        new Domain(7, 7, '17 months'),
        new Domain(8, 8, '18 months'),
        new Domain(9, 9, '19 months'),
        new Domain(10, 10, '20 months'),
        new Domain(11, 11, '21 months'),
        new Domain(12, 12, '22 months'),
        new Domain(13, 13, '23 months'),
        new Domain(14, 14, '2 years'),
        new Domain(15, 15, '3 years'),
        new Domain(16, 16, '4 years'),
        new Domain(17, 17, '5 years'),
        new Domain(18, 18, '6 years'),
        new Domain(19, 19, '7 years'),
        new Domain(20, 20, '8 years'),
        new Domain(21, 21, '9 years'),
        new Domain(22, 22, '10-12 years'),
        new Domain(23, 23, '13-15 years'),
        new Domain(24, 24, '16-17 years'),
        new Domain(25, 25, '18 years or older'),
        new Domain(26, 26, 'Don\'t know')
    ],
    3: [
        new Domain(1, 1, 'Less than 6 months'),
        new Domain(2, 2, '6-11 months'),
        new Domain(3, 3, '12-17 months'),
        new Domain(4, 4, '18-23 months'),
        new Domain(5, 5, '2 years'),
        new Domain(6, 6, '3 years'),
        new Domain(7, 7, '4 years'),
        new Domain(8, 8, '5 years'),
        new Domain(9, 9, '6 years'),
        new Domain(10, 10, '7 years'),
        new Domain(11, 11, '8 years'),
        new Domain(12, 12, '9 years'),
        new Domain(13, 13, '10-12 years'),
        new Domain(14, 14, '13-15 years'),
        new Domain(15, 15, '16-17 years')
    ],
    4: [
        new Domain(1, 1, 'Less than 12 months'),
        new Domain(2, 2, '12 months'),
        new Domain(3, 3, '13 months'),
        new Domain(4, 4, '14 months'),
        new Domain(5, 5, '15 months'),
        new Domain(6, 6, '16 months'),
        new Domain(7, 7, '17 months'),
        new Domain(8, 8, '18 months'),
        new Domain(9, 9, '19 months'),
        new Domain(10, 10, '20 months'),
        new Domain(11, 11, '21 months'),
        new Domain(12, 12, '22 months'),
        new Domain(13, 13, '23 months'),
        new Domain(14, 14, '2 years'),
        new Domain(15, 15, '3 years'),
        new Domain(16, 16, '4-6 years'),
        new Domain(17, 17, '7 years or older'),
        new Domain(18, 18, 'Don\'t know')
    ],
    5: [
        new Domain(1, 1, '12'),
        new Domain(2, 2, '13'),
        new Domain(3, 3, '14'),
        new Domain(4, 4, '15'),
        new Domain(5, 5, '16'),
        new Domain(6, 6, '17'),
        new Domain(7, 7, '18'),
        new Domain(8, 8, '19'),
        new Domain(9, 9, '20'),
        new Domain(10, 10, '21'),
        new Domain(11, 11, '22'),
        new Domain(12, 12, '23'),
        new Domain(13, 13, '24'),
        new Domain(14, 14, '25'),
        new Domain(15, 15, '26'),
        new Domain(16, 16, '27'),
        new Domain(17, 17, '28'),
        new Domain(18, 18, '29'),
        new Domain(19, 19, '30'),
        new Domain(20, 20, '31'),
        new Domain(21, 21, '32'),
        new Domain(22, 22, '33'),
        new Domain(23, 23, '34'),
        new Domain(24, 24, '35'),
        new Domain(25, 25, '36'),
        new Domain(26, 26, '37'),
        new Domain(27, 27, '38'),
        new Domain(28, 28, '39'),
        new Domain(29, 29, '40'),
        new Domain(30, 30, '41'),
        new Domain(31, 31, '42'),
        new Domain(32, 32, '43'),
        new Domain(33, 33, '44'),
        new Domain(34, 34, '45'),
        new Domain(35, 35, '46'),
        new Domain(36, 36, '47'),
        new Domain(37, 37, '48'),
        new Domain(38, 38, '49'),
        new Domain(39, 39, '50'),
        new Domain(40, 40, '51'),
        new Domain(41, 41, '52'),
        new Domain(42, 42, '53'),
        new Domain(43, 43, '54'),
        new Domain(44, 44, '55'),
        new Domain(45, 45, 'Over 55'),
        new Domain(46, 46, 'Don\'t know')
    ],
    6: [
        new Domain(1, 1, '0-3 months'),
        new Domain(2, 2, '4-6 months'),
        new Domain(3, 3, '7-12 months'),
        new Domain(4, 4, 'More than 12 months'),
        new Domain(5, 5, 'Don\'t know')
    ],
    7: [
        new Domain(1, 1, 'Less than 12 months'),
        new Domain(2, 2, '12 months'),
        new Domain(3, 3, '13 months'),
        new Domain(4, 4, '14 months'),
        new Domain(5, 5, '15 months'),
        new Domain(6, 6, '16 months'),
        new Domain(7, 7, '17 months'),
        new Domain(8, 8, '18 months'),
        new Domain(9, 9, '19 months'),
        new Domain(10, 10, '20 months'),
        new Domain(11, 11, '21 months'),
        new Domain(12, 12, '22 months'),
        new Domain(13, 13, '23 months'),
        new Domain(14, 14, '2 years'),
        new Domain(15, 15, '3 years'),
        new Domain(16, 16, '4 years'),
        new Domain(17, 17, '5 years'),
        new Domain(18, 18, '6 years'),
        new Domain(19, 19, '7 years'),
        new Domain(20, 20, '8 years'),
        new Domain(21, 21, '9 years'),
        new Domain(22, 22, '10-12 years'),
        new Domain(23, 23, '13-15 years'),
        new Domain(24, 24, '16-17 years'),
        new Domain(25, 25, 'Don\'t know'),
        new Domain(26, 26, 'No concern before ASD diagnosis was given')
    ],
    8: [
        new Domain(1, 1, 'Professional in a health care setting'),
        new Domain(2, 2, 'Professional in an educational setting'),
        new Domain(3, 3, 'Don\'t know'),
        new Domain(4, 4, 'Other')
    ],
    9: [
        new Domain(1, 1, 'Dummy')
    ],
    10: [
        new Domain(1, 1, 'Less than high school (did not receive a high school diploma or equivalent)'),
        new Domain(2, 2, 'High school graduate (or equivalent)'),
        new Domain(3, 3, 'Some college (1-4 years, no degree)'),
        new Domain(4, 4, 'Associate\'s degree (including occupational or academic degrees)'),
        new Domain(5, 5, 'Bachelor\'s degree (BA, BS, AB, etc.)'),
        new Domain(6, 6, 'Master\'s degree, professional school degree, or doctorate degree (MA, MS, MSW, MENG, MD, DDC, JD, PhD, ScD, EdD, etc.)'),
        new Domain(7, 7, 'Don\'t know')
    ],
    11: [
        new Domain(1, 1, 'Hispanic or Latino'),
        new Domain(2, 2, 'Not Hispanic or Latino'),
        new Domain(3, 3, 'Prefer not to answer')
    ],
    12: [
        new Domain(1, 1, 'proband'),
        new Domain(2, 2, 'mother'),
        new Domain(3, 3, 'father')
    ],
    13: [
        new Domain(1, 1, 'Always'),
        new Domain(2, 2, 'Often'),
        new Domain(3, 3, 'Sometimes'),
        new Domain(4, 4, 'Rarely'),
        new Domain(5, 5, 'Never'),
        new Domain(6, 6, 'Don\'t know')
    ],
    14: [
        new Domain(1, 1, 'Never'),
        new Domain(2, 2, 'Less than once per week'),
        new Domain(3, 3, '1-6 times per week'),
        new Domain(4, 4, '1+ times per day'),
        new Domain(5, 5, 'Don\'t know'),
        new Domain(6, 6, 'Prefer not to answer')
    ],
    15: [
        new Domain(1, 1, 'Never'),
        new Domain(2, 2, 'Less than once per week'),
        new Domain(3, 3, '1-6 times per week'),
        new Domain(4, 4, '1-2 times per day'),
        new Domain(5, 5, '3 or more times per day'),
        new Domain(6, 6, 'Don\'t know'),
        new Domain(7, 7, 'Prefer not to answer')
    ],
    16: [
        new Domain(1, 1, '2'),
        new Domain(2, 2, '3'),
        new Domain(3, 3, '4'),
        new Domain(4, 4, '5'),
        new Domain(5, 5, '6'),
        new Domain(6, 6, '7'),
        new Domain(7, 7, '8'),
        new Domain(8, 8, '9')
    ],
    17: [
        new Domain(1, 1, '0'),
        new Domain(2, 2, '1'),
        new Domain(3, 3, '2'),
        new Domain(4, 4, '3'),
        new Domain(5, 5, '4'),
        new Domain(6, 6, '5'),
        new Domain(7, 7, '6'),
        new Domain(8, 8, '7'),
        new Domain(9, 9, '8'),
        new Domain(10, 10, '9'),
        new Domain(11, 11, '10'),
        new Domain(12, 12, '11')
    ],
    18: [
        new Domain(1, 1, '1'),
        new Domain(2, 2, '2'),
        new Domain(3, 3, '3'),
        new Domain(4, 4, '4'),
        new Domain(5, 5, '5+'),
        new Domain(6, 6, 'Don\'t know')
    ],
    19: [
        new Domain(1, 1, '0'),
        new Domain(2, 2, '1'),
        new Domain(3, 3, '2'),
        new Domain(4, 4, '3'),
        new Domain(5, 5, '4+'),
        new Domain(6, 6, 'Don\'t know')
    ],
    20: [
        new Domain(1, 1, 'Work in an office environment'),
        new Domain(2, 2, 'Retail/sales/cashier'),
        new Domain(3, 3, 'Food preparation/food server/waiter or waitress'),
        new Domain(4, 4, 'Health care worker/doctor/nurse'),
        new Domain(5, 5, 'Janitor/housekeeper'),
        new Domain(6, 6, 'Warehouse/stockroom'),
        new Domain(7, 7, 'Manufacturing/factory'),
        new Domain(8, 8, 'Repair services/mechanic/plumber'),
        new Domain(9, 9, 'Miner '),
        new Domain(10, 10, 'Welder '),
        new Domain(11, 11, 'Teacher/teacher\'s aid'),
        new Domain(12, 12, 'Student'),
        new Domain(13, 13, 'Construction'),
        new Domain(14, 14, 'Laboratory technician/scientist'),
        new Domain(15, 15, 'Public safety (police, firefighter, security guard)'),
        new Domain(16, 16, 'Agriculture/farming'),
        new Domain(17, 17, 'Stay-at-home parent'),
        new Domain(18, 18, 'Unemployed'),
        new Domain(19, 19, 'Unknown'),
        new Domain(20, 20, 'Prefer not to answer'),
        new Domain(21, 21, 'Other (Please indicate)')
    ],
    21: [
        new Domain(1, 1, 'American Indian or Alaska Native <tooltip id="6"/>'),
        new Domain(2, 2, 'Asian <tooltip id="4"/>'),
        new Domain(3, 3, 'Black or African American <tooltip id="3"/>'),
        new Domain(4, 4, 'Native Hawaiian or Other Pacific Islander <tooltip id="5"/>'),
        new Domain(5, 5, 'White <tooltip id="2"/>'),
        new Domain(6, 6, 'Prefer not to answer')
    ],
    22: [
        new Domain(1, 1, 'Please do not contact me again.'),
        new Domain(2, 2, 'You can contact me again.')
    ],
    23: [
        new Domain(1, 1, 'Male'),
        new Domain(2, 2, 'Female')
    ],
    24: [
        new Domain(1, 1, 'AL'),
        new Domain(2, 2, 'AK'),
        new Domain(3, 3, 'AZ'),
        new Domain(4, 4, 'AR'),
        new Domain(5, 5, 'CA'),
        new Domain(6, 6, 'CO'),
        new Domain(7, 7, 'CT'),
        new Domain(8, 8, 'DE'),
        new Domain(9, 9, 'DC'),
        new Domain(10, 10, 'FL'),
        new Domain(11, 11, 'GA'),
        new Domain(12, 12, 'HI'),
        new Domain(13, 13, 'ID'),
        new Domain(14, 14, 'IL'),
        new Domain(15, 15, 'IN'),
        new Domain(16, 16, 'IA'),
        new Domain(17, 17, 'KS'),
        new Domain(18, 18, 'KY'),
        new Domain(19, 19, 'LA'),
        new Domain(20, 20, 'ME'),
        new Domain(21, 21, 'MD'),
        new Domain(22, 22, 'MA'),
        new Domain(23, 23, 'MI'),
        new Domain(24, 24, 'MN'),
        new Domain(25, 25, 'MS'),
        new Domain(26, 26, 'MO'),
        new Domain(27, 27, 'MT'),
        new Domain(28, 28, 'NE'),
        new Domain(29, 29, 'NV'),
        new Domain(30, 30, 'NH'),
        new Domain(31, 31, 'NJ'),
        new Domain(32, 32, 'NM'),
        new Domain(33, 33, 'NY'),
        new Domain(34, 34, 'NC'),
        new Domain(35, 35, 'ND'),
        new Domain(36, 36, 'OH'),
        new Domain(37, 37, 'OK'),
        new Domain(38, 38, 'OR'),
        new Domain(39, 39, 'PA'),
        new Domain(40, 40, 'RI'),
        new Domain(41, 41, 'SC'),
        new Domain(42, 42, 'SD'),
        new Domain(43, 43, 'TN'),
        new Domain(44, 44, 'TX'),
        new Domain(45, 45, 'UT'),
        new Domain(46, 46, 'VT'),
        new Domain(47, 47, 'VA'),
        new Domain(48, 48, 'WA'),
        new Domain(49, 49, 'WV'),
        new Domain(50, 50, 'WI'),
        new Domain(51, 51, 'WY')
    ],
    25: [
        new Domain(1, 1, 'If you are a parent or guardian taking the survey for a child, click here.'),
        new Domain(2, 2, 'If you are a legally authorized representative taking the survey for another adult, click here.'),
        new Domain(3, 3, 'If you are an adult taking the survey on behalf of yourself, click here.')
    ],
    26: [
        new Domain(1, 5, 'Speaks in 3 or more word combinations'),
        new Domain(2, 4, 'Speaks in 2 words combinations'),
        new Domain(3, 3, 'Uses more than 10 single words'),
        new Domain(4, 2, 'Uses 1-10 single words'),
        new Domain(5, 1, 'Does not use any words'),
        new Domain(6, 6, 'Prefer not to answer')
    ],
    27: [
        new Domain(1, 1, 'Private well'),
        new Domain(2, 2, 'Public water supply'),
        new Domain(3, 3, 'Bottled water'),
        new Domain(4, 4, 'Don\'t know')
    ],
    28: [
        new Domain(1, 1, '24 weeks or less'),
        new Domain(2, 2, '25-26 weeks'),
        new Domain(3, 3, '27-28 weeks'),
        new Domain(4, 4, '29-30 weeks'),
        new Domain(5, 5, '31-32 weeks'),
        new Domain(6, 6, '33-34 weeks'),
        new Domain(7, 7, '35-36 weeks'),
        new Domain(8, 8, '37-38 weeks'),
        new Domain(9, 9, '39-40 weeks'),
        new Domain(10, 10, '41-42 weeks'),
        new Domain(11, 11, '43 weeks or more'),
        new Domain(12, 12, 'Don\'t know')
    ],
    29: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No')
    ],
    30: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No'),
        new Domain(3, 3, 'Don\'t know')
    ],
    31: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No'),
        new Domain(3, 3, 'Don\'t know'),
        new Domain(4, 4, 'Not Applicable')
    ],
    32: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No'),
        new Domain(3, 3, 'Don\'t know'),
        new Domain(4, 4, 'Prefer not to answer')
    ],
    33: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No'),
        new Domain(3, 3, 'Don\'t know'),
        new Domain(4, 4, 'Never had these skills'),
        new Domain(5, 5, 'If yes, what was the child\'s age when you first noticed this change in their development?')
    ],
    34: [
        new Domain(1, 1, 'Yes'),
        new Domain(2, 2, 'No'),
        new Domain(3, 3, 'Prefer not to answer')
    ],
    35: [
        new Domain(1, 1, 'Write code for Today minus 17 years'),
        new Domain(2, 2, 'Write code for Today minus 17 years'),
        new Domain(3, 3, 'Write code for Today minus 17 years')
    ],
    36: [
        new Domain(1, 1, 'Write code for Today minus 99 years'),
        new Domain(2, 2, 'Write code for Today minus 18 years'),
        new Domain(3, 3, 'Write code for Today minus 18 years')
    ],
    37: [
        new Domain(1, 1, 'Write code for Today minus 99 years'),
        new Domain(2, 2, 'Write code for Today minus 18 years'),
        new Domain(3, 3, 'Write code for Today minus 18 years')
    ],
    38: [
        new Domain(1, 1, 'Write code for Today minus 99 years'),
        new Domain(2, 2, 'Write code for Today minus 10 years'),
        new Domain(3, 3, 'Write code for Today minus 20 years')
    ],
    39: [
        new Domain(1, 1, 'Write code for Today minus 99 years'),
        new Domain(2, 2, 'Write code for Today minus 10 years'),
        new Domain(3, 3, 'Write code for Today minus 20 years')
    ],
    40: [
        new Domain(1, 1, 'Write code for Today minus 99 years'),
        new Domain(2, 2, 'Write code for Today minus 10 years'),
        new Domain(3, 3, 'Write code for Today minus 20 years')
    ],
    41: [
        new Domain(1, 1, 'January'),
        new Domain(2, 2, 'February'),
        new Domain(3, 3, 'March'),
        new Domain(4, 4, 'April'),
        new Domain(5, 5, 'May'),
        new Domain(6, 6, 'June'),
        new Domain(7, 7, 'July'),
        new Domain(8, 8, 'August'),
        new Domain(9, 9, 'September'),
        new Domain(10, 10, 'October'),
        new Domain(11, 11, 'November'),
        new Domain(12, 12, 'December')
    ],
    42: [
        new Domain(1, 1, 'Write code for earliest_year(residence_person)'),
        new Domain(2, 2, 'Write code for Date().getFullYear()'),
        new Domain(3, 3, null)
    ],
    43: [
        new Domain(1, 1, 'Unsure of address during this time period'),
        new Domain(2, 2, 'Lived outside of the 50 US states and the District of Columbia during this time period')
    ],
    44: [
        new Domain(1, 52, 'Not born in the 50 US states or DC'),
        new Domain(2, 1, 'AL'),
        new Domain(3, 2, 'AK'),
        new Domain(4, 3, 'AZ'),
        new Domain(5, 4, 'AR'),
        new Domain(6, 5, 'CA'),
        new Domain(7, 6, 'CO'),
        new Domain(8, 7, 'CT'),
        new Domain(9, 8, 'DE'),
        new Domain(10, 9, 'DC'),
        new Domain(11, 10, 'FL'),
        new Domain(12, 11, 'GA'),
        new Domain(13, 12, 'HI'),
        new Domain(14, 13, 'ID'),
        new Domain(15, 14, 'IL'),
        new Domain(16, 15, 'IN'),
        new Domain(17, 16, 'IA'),
        new Domain(18, 17, 'KS'),
        new Domain(19, 18, 'KY'),
        new Domain(20, 19, 'LA'),
        new Domain(21, 20, 'ME'),
        new Domain(22, 21, 'MD'),
        new Domain(23, 22, 'MA'),
        new Domain(24, 23, 'MI'),
        new Domain(25, 24, 'MN'),
        new Domain(26, 25, 'MS'),
        new Domain(27, 26, 'MO'),
        new Domain(28, 27, 'MT'),
        new Domain(29, 28, 'NE'),
        new Domain(30, 29, 'NV'),
        new Domain(31, 30, 'NH'),
        new Domain(32, 31, 'NJ'),
        new Domain(33, 32, 'NM'),
        new Domain(34, 33, 'NY'),
        new Domain(35, 34, 'NC'),
        new Domain(36, 35, 'ND'),
        new Domain(37, 36, 'OH'),
        new Domain(38, 37, 'OK'),
        new Domain(39, 38, 'OR'),
        new Domain(40, 39, 'PA'),
        new Domain(41, 40, 'RI'),
        new Domain(42, 41, 'SC'),
        new Domain(43, 42, 'SD'),
        new Domain(44, 43, 'TN'),
        new Domain(45, 44, 'TX'),
        new Domain(46, 45, 'UT'),
        new Domain(47, 46, 'VT'),
        new Domain(48, 47, 'VA'),
        new Domain(49, 48, 'WA'),
        new Domain(50, 49, 'WV'),
        new Domain(51, 50, 'WI'),
        new Domain(52, 51, 'WY')
    ],
    45: [
        new Domain(1, 1, '0'),
        new Domain(2, 2, '1'),
        new Domain(3, 3, '2'),
        new Domain(4, 4, '3'),
        new Domain(5, 5, '4'),
        new Domain(6, 6, '5'),
        new Domain(7, 7, '6'),
        new Domain(8, 8, '7'),
        new Domain(9, 9, '8'),
        new Domain(10, 10, '9'),
        new Domain(11, 11, '10'),
        new Domain(12, 12, '11'),
        new Domain(13, 13, '12')
    ],
    46: [
        new Domain(1, 1, 'lbs'),
        new Domain(2, 2, '0'),
        new Domain(3, 3, '999')
    ],
    47: [
        new Domain(1, 1, 'Full time/part time employment in an independent position'),
        new Domain(2, 2, 'Full time/part time employment with a job coach or other help at work'),
        new Domain(3, 3, 'Internship or work study program'),
        new Domain(4, 4, 'Other')
    ],
    48: [
        new Domain(1, 1, 'Want to work but can\'t find a job'),
        new Domain(2, 2, 'Not currently seeking employment'),
        new Domain(3, 3, 'Other')
    ],
    49: [
        new Domain(1, 27, 'Does not speak any word'),
        new Domain(2, 1, 'Less than 12 months'),
        new Domain(3, 2, '12 months'),
        new Domain(4, 3, '13 months'),
        new Domain(5, 4, '14 months'),
        new Domain(6, 5, '15 months'),
        new Domain(7, 6, '16 months'),
        new Domain(8, 7, '17 months'),
        new Domain(9, 8, '18 months'),
        new Domain(10, 9, '19 months'),
        new Domain(11, 10, '20 months'),
        new Domain(12, 11, '21 months'),
        new Domain(13, 12, '22 months'),
        new Domain(14, 13, '23 months'),
        new Domain(15, 14, '2 years'),
        new Domain(16, 15, '3 years'),
        new Domain(17, 16, '4 years'),
        new Domain(18, 17, '5 years'),
        new Domain(19, 18, '6 years'),
        new Domain(20, 19, '7 years'),
        new Domain(21, 20, '8 years'),
        new Domain(22, 21, '9 years'),
        new Domain(23, 22, '10-12 years'),
        new Domain(24, 23, '13-15 years'),
        new Domain(25, 24, '16-17 years'),
        new Domain(26, 25, '18 years or older'),
        new Domain(27, 26, 'Don\'t know')
    ],
    50: [
        new Domain(1, 27, 'I do not speak any word'),
        new Domain(2, 1, 'Less than 12 months'),
        new Domain(3, 2, '12 months'),
        new Domain(4, 3, '13 months'),
        new Domain(5, 4, '14 months'),
        new Domain(6, 5, '15 months'),
        new Domain(7, 6, '16 months'),
        new Domain(8, 7, '17 months'),
        new Domain(9, 8, '18 months'),
        new Domain(10, 9, '19 months'),
        new Domain(11, 10, '20 months'),
        new Domain(12, 11, '21 months'),
        new Domain(13, 12, '22 months'),
        new Domain(14, 13, '23 months'),
        new Domain(15, 14, '2 years'),
        new Domain(16, 15, '3 years'),
        new Domain(17, 16, '4 years'),
        new Domain(18, 17, '5 years'),
        new Domain(19, 18, '6 years'),
        new Domain(20, 19, '7 years'),
        new Domain(21, 20, '8 years'),
        new Domain(22, 21, '9 years'),
        new Domain(23, 22, '10-12 years'),
        new Domain(24, 23, '13-15 years'),
        new Domain(25, 24, '16-17 years'),
        new Domain(26, 25, '18 years or older'),
        new Domain(27, 26, 'Don\'t know')
    ]
};
