import { SeedDataPageQuestions } from '../types/database-data/page-questions';
import { PageQuestion } from '../types/database-data/page-question';

export var pageQuestionDict: SeedDataPageQuestions = {
    1: [
        new PageQuestion(1,1,100,0,'IN',null,null,null,1,30,3,null,'The National Collaborative Autism Project aims to gather data on people both with and without a diagnosis of autism spectrum disorder (ASD). In this survey, we ask for basic information about the person of interest (for example, a child with ASD), such as date of birth and home address(es) at time of birth. We will then link environmental exposure data to the information you provide.  For example, address information is used to find the nearest air quality monitor(s), so that air pollution exposure data can be linked with your survey responses.  Your input will help researchers better understand links between exposure to environmental pollutants and risk of developing ASD. This project is led by Dr. Marie Lynn Miranda at Rice University, and is funded by the National Institute of Mental Health, part of the National Institutes of Health. You must be 18 or older to take the survey.','The National Collaborative Autism Project aims to gather data on people both with and without a diagnosis of autism spectrum disorder (ASD). In this survey, we ask for basic information about the person of interest (for example, a child with ASD), such as date of birth and home address(es) at time of birth. We will then link environmental exposure data to the information you provide.  For example, address information is used to find the nearest air quality monitor(s), so that air pollution exposure data can be linked with your survey responses.  Your input will help researchers better understand links between exposure to environmental pollutants and risk of developing ASD. This project is led by Dr. Marie Lynn Miranda at Rice University, and is funded by the National Institute of Mental Health, part of the National Institutes of Health. You must be 18 or older to take the survey.','The National Collaborative Autism Project aims to gather data on people both with and without a diagnosis of autism spectrum disorder (ASD). In this survey, we ask for basic information about the person of interest (for example, a child with ASD), such as date of birth and home address(es) at time of birth. We will then link environmental exposure data to the information you provide.  For example, address information is used to find the nearest air quality monitor(s), so that air pollution exposure data can be linked with your survey responses.  Your input will help researchers better understand links between exposure to environmental pollutants and risk of developing ASD. This project is led by Dr. Marie Lynn Miranda at Rice University, and is funded by the National Institute of Mental Health, part of the National Institutes of Health. You must be 18 or older to take the survey.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(1,2,200,0,'IN',null,null,null,16,18,2,null,'<!-- No explicit question as there are no Next button on this page -->','<!-- No explicit question as there are no Next button on this page -->','<!-- No explicit question as there are no Next button on this page -->',25,25,25,'respondent_type',null,null,null,null,null,'respondent_type' ) 
    ],
    2: [
        new PageQuestion(2,1,300,0,'IN',null,null,null,1,8,3,null,'<Insert consent introductory text here>','<Insert consent introductory text here>','<Insert consent introductory text here>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(2,2,400,0,'IN',null,null,null,13,3,2,null,'I agree.  Proceed to the survey.','I agree.  Proceed to the survey.','I agree.  Proceed to the survey.',29,29,29,'initial_consent',null,null,null,null,null,'initial_consent' ) 
    ],
    3: [
        new PageQuestion(3,1,500,0,'BS',null,null,null,2,8,3,null,'Child Characteristics','Individual/Personal Characteristics','Individual/Personal Characteristics',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(3,2,600,0,'BS',null,null,null,3,8,3,null,'You have chosen to complete the survey about a child. We ask about the child\'s characteristics to collect basic data on each person.','You have chosen to complete the survey on behalf of an adult that you legally represent. We ask a few questions about the individual.','You have chosen to complete the survey about yourself. We ask you a few questions about yourself.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(3,3,700,0,'BS',null,null,null,4,1,2,null,'Has the child ever been diagnosed with ASD <tooltip id="1"/>, which includes Asperger syndrome, childhood disintegrative disorder, and pervasive developmental disorders not otherwise specified?','Has the individual ever been diagnosed with ASD <tooltip id="1"/>,  which includes Asperger syndrome, childhood disintegrative disorder, and pervasive developmental disorders not otherwise specified (PDD-NOS)? ','Have you ever been diagnosed with ASD <tooltip id="1"/>,  which includes Asperger syndrome, childhood disintegrative disorder, and pervasive developmental disorders not otherwise specified (PDD-NOS)? ',29,29,29,'asd_yes_no',null,null,null,null,null,'asd_yes_no' ) ,
        new PageQuestion(3,4,800,0,'BS',null,null,null,4,9,2,null,'What is the child\'s date of birth? (mm/dd/yyyy):','What is the individual\'s date of birth? (mm/dd/yyyy):','What is your date of birth? (mm/dd/yyyy):',35,36,37,'proband_DOB','Birthday',null,null,null,null,'proband_DOB' ) 
    ],
    4: [
        new PageQuestion(4,1,900,0,'BS',null,null,null,4,1,1,null,'What was the child\'s sex at birth?','What was the individual\'s sex at birth?','What was your sex at birth?',23,23,23,'sex_at_birth',null,null,null,null,null,'sex_at_birth' ) ,
        new PageQuestion(4,2,1000,0,'BS',null,null,null,4,3,1,null,'What is the child\'s race?  (Select all that apply.)','What is the individual\'s race?  (Select all that apply.) ','What is your race?  (Select all that apply.) ',21,21,21,'race',null,null,null,null,null,'race' ) ,
        new PageQuestion(4,3,1100,0,'BS',null,null,null,4,1,1,null,'What is the child\'s ethnicity  <tooltip id="7"/> ?','What is the individual\'s ethnicity  <tooltip id="7"/> ?','What is your ethnicity  <tooltip id="7"/> ?',11,11,11,'ethnicity',null,null,null,null,null,'ethnicity' ) ,
        new PageQuestion(4,4,1200,1,'BS',37,37,37,4,16,3,null,'What is the child\'s height?',null,null,null,null,null,'height_std',null,null,null,null,null,null ) ,
        new PageQuestion(4,5,1500,0,'BS',37,37,37,18,6,1,null,'What is the child\'s weight in pounds?',null,null,46,46,46,'weight_std','Weight',1,1,1,'Please enter a valid weight.','weight_std' ) 
    ],
    8: [
        new PageQuestion(8,1,2400,0,'GD',null,null,null,2,8,3,null,'Birth Certificate Information for Child','Birth Certificate Information for the individual','Your birth Certificate Information ',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(8,2,2500,0,'GD',null,null,null,3,8,3,null,'<strong>Enter this information as it appears on the child\'s birth certificate.</strong> We ask for this to create an identifier that is unique to the child. This identifier can link the child to new or existing research data. Birth certificate data is never shared.','<strong>Enter this information as it appears on the individual\'s birth certificate</strong>. We ask for this to create an identifier that is unique to the individual. This identifier can link them to new or existing research data. Birth certificate data is never shared.','<strong>Enter this information as it appears on your birth certificate</strong>. We ask for this to create an identifier that is unique to you. This identifier can link you to new or existing research data. Birth certificate data is never shared.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(8,3,2600,0,'GD',null,null,null,7,6,1,null,'First Name','First Name','First Name',null,null,null,'firstName','First Name',null,null,null,null,'firstName' ) ,
        new PageQuestion(8,4,2700,0,'GD',null,null,null,7,6,0,null,'Middle Name','Middle Name','Middle Name',null,null,null,'middleName','Middle Name',null,null,null,null,null ) ,
        new PageQuestion(8,5,2800,0,'GD',null,null,null,7,6,1,null,'Last Name','Last Name','Last Name',null,null,null,'lastName','Last Name',null,null,null,null,'lastName' ) ,
        new PageQuestion(8,6,2900,0,'GD',1,1,1,4,1,1,null,'Does the child have a middle name?','Does the individual have a middle name?','Do you have a middle name?',29,29,29,'middleName_confirm',null,null,null,null,null,'middleName_confirm' ) ,
        new PageQuestion(8,7,3000,0,'GD',null,null,null,7,6,1,null,'City of birth (as it appears on birth certificate. U.S. cities only)','City of birth (as it appears on birth certificate. U.S. cities only)','City of birth (as it appears on birth certificate. U.S. cities only)',null,null,null,'birthCertCity','City',null,null,null,null,'birthCertCity' ) ,
        new PageQuestion(8,8,3050,0,'GD',null,null,null,4,7,0,null,'State','State','State',24,24,24,'proband_state_GUID',null,null,null,null,null,null ) ,
        new PageQuestion(8,9,3100,0,'GD',null,null,null,2,8,3,null,'Birth Certificate Information for Biological Mother','Birth Certificate Information for Biological Mother','Birth Certificate Information for Biological Mother',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(8,10,3200,0,'GD',null,null,null,3,8,3,null,'<strong>Enter this information as it appears on the birth certificate of the child\'s biological mother</strong>. We ask for this to create an identifier that is unique to the child\'s mother. This identifier can link the mother to new or existing research data. Birth certificate data is never shared.','<strong>Enter this information as it appears on the birth certificate of the individual\'s biological mother</strong>. We ask for this to create an identifier that is unique to the individual\'s mother. This identifier can link the mother to new or existing research data. Birth certificate data is never shared.','<strong>Enter this information as it appears on the birth certificate of your biological mother</strong>. We ask for this to create an identifier that is unique to your mother. This identifier can link your mother to new or existing research data. Birth certificate data is never shared.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(8,11,3300,0,'GD',null,null,null,7,6,1,null,'First Name','First Name','First Name',null,null,null,'firstNameMother','First Name',null,null,null,null,'firstNameMother' ) ,
        new PageQuestion(8,12,3400,0,'GD',null,null,null,7,6,0,null,'Middle Name','Middle Name','Middle Name',null,null,null,'middleNameMother','Middle Name',null,null,null,null,null ) ,
        new PageQuestion(8,13,3500,0,'GD',null,null,null,7,6,1,null,'Last Name','Last Name','Last Name',null,null,null,'lastNameMother','Last Name',null,null,null,null,'lastNameMother' ) ,
        new PageQuestion(8,14,3600,0,'GD',null,null,null,8,9,1,null,'Date of birth (mm/dd/yyyy)','Date of birth (mm/dd/yyyy)','Date of birth (mm/dd/yyyy)',38,39,40,'mother_DOB','Birthday',null,null,null,null,'mother_DOB' ) ,
        new PageQuestion(8,15,3700,0,'GD',null,null,null,7,6,1,null,'City of birth (as it appears on birth certificate)','City of birth (as it appears on birth certificate)','City of birth (as it appears on birth certificate)',null,null,null,'birthCertCityMother','City',null,null,null,null,'birthCertCityMother' ) ,
        new PageQuestion(8,16,3750,0,'GD',null,null,null,4,7,0,null,'State','State','State',44,44,44,'mother_state_GUID',null,null,null,null,null,null ) 
    ],
    5: [
        new PageQuestion(5,1,1600,0,'RS',null,null,null,2,8,3,null,'Residential Information','Residential Information','Residential Information',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(5,2,1700,0,'RS',null,null,null,3,8,3,null,'We ask for addresses where the child and parents lived to connect the location with other data. Even limited information about location helps. <u>Please enter as much as you can remember.</u>','We ask for addresses where the individual and parents lived to connect the location with other data. Even limited information about location helps. <u>Please enter as much as you can remember.</u>','We ask for addresses where you and parents lived to connect the location with other data. Even limited information about location helps. <u>Please enter as much as you can remember.</u>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(5,3,1800,0,'RS',null,null,null,4,8,1,null,'Where did the <u>child</u> live from birth through the first year of their life?','Where did the <u>individual</u> live from birth through the first year of their life?','Where did <u>you</u> live from birth through the first year of your life?',null,null,null,null,null,null,null,null,'<!--special case-->','<!--special case-->' ) ,
        new PageQuestion(5,4,1900,0,'RS',null,null,null,15,8,3,null,'Please include all addresses during this 1-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 1-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 1-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.',null,null,null,null,null,null,null,null,null,null ) 
    ],
    6: [
        new PageQuestion(6,1,2000,0,'RS',null,null,null,4,8,1,null,'Where did the child\'s biological <u>mother</u> live for the 2 years prior to the child\'s birth? ','Where did the individual\'s biological <u>mother</u> live for the 2 years prior to the individual\'s birth? ','Where did your biological <u>mother</u> live for the 2 years prior to your birth? ',null,null,null,null,null,null,null,null,'<!--special case-->','<!--special case-->' ) ,
        new PageQuestion(6,2,2100,0,'RS',null,null,null,15,8,3,null,'Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.',null,null,null,null,null,null,null,null,null,null ) 
    ],
    7: [
        new PageQuestion(7,1,2200,0,'RS',null,null,null,4,8,1,null,'Where did the child\'s biological <u>father</u> live for the 2 years prior to the child\'s birth?','Where did the individual\'s biological <u>father</u> live for the 2 years prior to the individual\'s birth? ','Where did your biological <u>father</u> live for the 2 years prior to your birth? ',null,null,null,null,null,null,null,null,'<!--special case-->','<!--special case-->' ) ,
        new PageQuestion(7,2,2300,0,'RS',null,null,null,15,8,3,null,'Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.','Please include all addresses during this 2-year period, along with dates of residence. Click \'Save Address\' to save each address you enter. When all addresses have been entered, click \'Next\'.',null,null,null,null,null,null,null,null,null,null ) 
    ],
    9: [
        new PageQuestion(9,1,3900,0,'DI',3,3,3,3,8,3,null,'The next set of questions is about the child\'s ASD diagnosis. Please answer as best you can. You indicated earlier in the survey that the child received a diagnosis of ASD.','The next set of questions is about the individual\'s ASD diagnosis. Please answer as best you can. You indicated earlier in the survey that the individual received a diagnosis of ASD.','The next set of questions are about your ASD diagnosis. Please answer as best you can. You indicated earlier in the survey that your received a diagnosis of ASD.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(9,2,4000,0,'DI',3,3,3,4,7,1,null,'How old was the child when you or anyone else started to be concerned about their development?','How old was the individual when you or anyone else started to be concerned about their development?','How old were you when your parents or anyone else started to be concerned about your development?',7,1,7,'dev_concern_age',null,null,null,null,null,'dev_concern_age' ) ,
        new PageQuestion(9,3,4100,0,'DI',3,3,3,4,7,1,null,'About how old was the child when they were diagnosed with ASD?','About how old was the individual when they were diagnosed with ASD?','About how old were you when you were diagnosed with ASD?',1,2,2,'ASD_diag_age',null,null,null,null,null,'ASD_diag_age' ) ,
        new PageQuestion(9,4,4200,1,'DI',3,3,3,4,4,1,null,'Who diagnosed the child with ASD?','Who diagnosed the individual with ASD?','Who diagnosed you with ASD?',8,8,8,'ASD_diag_src',null,null,null,null,null,'ASD_diag_src' ) 
    ],
    10: [
        new PageQuestion(10,1,4500,0,'PH',null,null,null,3,8,3,null,'The next set of questions is about the child\'s symptoms, behaviors, and development. Please answer as best you can.','The next set of questions is about the individual\'s symptoms, behaviors, and development as a child. Please answer as best you can.','The next set of questions is about your symptoms, behaviors, and development as a child. Please answer as best you can.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(10,2,4600,1,'PH',null,null,null,4,10,3,null,'Did the child display the following developmental milestones?','As a child, did the individual display the following developmental milestones?','As a child, did you display the following developmental milestones?',31,31,31,null,null,null,null,null,null,null ) ,
        new PageQuestion(10,3,4950,1,'PH',null,null,null,4,12,3,null,'Did the child have any of the following behaviors or symptoms during any stage of development?','As a child, did the individual have any of the following symptoms during any stage of development? Answer as appropriate for the age.','As a child, did you have any of the following symptoms during any stage of development? Answer as appropriate for the age.',31,31,31,null,null,null,null,null,null,null ) 
    ],
    11: [
        new PageQuestion(11,1,6300,1,'PH',null,null,null,4,11,3,null,'Did the child:','Did the individual:','Did you:',33,33,33,null,null,null,null,null,null,null ) 
    ],
    12: [
        new PageQuestion(12,1,8000,0,'PH',null,null,null,4,1,1,null,'Does the child currently walk on their own?','Does the individual currently walk on their own?','Do you currently walk on your own?',33,33,33,'WalkByOneself',null,null,null,null,null,'WalkByOneself' ) ,
        new PageQuestion(12,2,8100,0,'PH',13,13,13,4,7,1,null,'How old was child when they first walked?','How old was the individual when they first walked?','How old were you when you first walked?',4,4,4,'WalkByOneselfAge','Please select',null,null,null,null,'WalkByOneselfAge' ) ,
        new PageQuestion(12,3,8200,0,'PH',37,37,37,4,1,1,null,'What best describes the child\'s current verbal skill?',null,null,26,26,26,'VerbalSkill',null,null,null,null,null,'VerbalSkill' ) ,
        new PageQuestion(12,4,8300,0,'PH',14,null,null,4,7,1,null,'At what age did the child say their first words?','At what age did the individual say their first words?','At what age did you say you first words?',1,49,50,'FirstWordsAge','Please select',null,null,null,null,'FirstWordsAge' ) ,
        new PageQuestion(12,5,8400,0,'PH',15,null,null,4,7,1,null,'At what age did they string two to three words together to express needs?','At what age did the individual string two to three words together to express needs?','At what age did you string two to three words together to express needs?',1,49,50,'StringWordsAge','Please select',null,null,null,null,'StringWordsAge' ) 
    ],
    13: [
        new PageQuestion(13,1,8500,1,'PH',null,null,null,4,10,3,null,'How often does the child currently:','As a child, how often did the individual:','As a child, how often did you:',13,13,13,null,null,null,null,null,null,null ) ,
        new PageQuestion(13,2,9000,1,'PH',null,null,null,4,10,3,null,'How often does the child currently:','As a child, how often did the individual:','As a child, how often did you:',13,13,13,null,null,null,null,null,null,null ) 
    ],
    14: [
        new PageQuestion(14,1,9800,1,'PH',null,null,null,4,10,3,null,'How often does the child currently:','As a child, how often did the individual:','As a child, how often did you:',13,13,13,null,null,null,null,null,null,null ) 
    ],
    15: [
        new PageQuestion(15,1,10700,0,'PH',null,null,null,4,8,3,null,'Has a physician ever diagnosed your child with any of the following?','Has a physician ever diagnosed the individual with any of the following?','Has a physician ever diagnosed you with any of the following?',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(15,2,10800,1,'PH',null,null,null,4,12,3,null,'Learning, developmental, behavior issues:','Learning, developmental, behavior issues:','Learning, developmental, behavior issues:',30,30,30,null,null,null,null,null,null,null ) ,
        new PageQuestion(15,3,11800,1,'PH',null,null,null,4,12,3,null,'Emotional health issues:','Emotional health issues:','Emotional health issues:',30,30,30,null,null,null,null,null,null,null ) ,
        new PageQuestion(15,4,12500,1,'PH',null,null,null,4,12,3,null,'Other health issues:','Other health issues:','Other health issues:',30,30,30,null,null,null,null,null,null,null ) 
    ],
    16: [
        new PageQuestion(16,1,13400,1,'PH',null,null,null,4,12,3,null,'Has the child ever experienced any of the following?','Has the individual ever experienced any of the following?','Have you ever experienced any of the following?',30,30,30,null,null,null,null,null,null,null ) 
    ],
    17: [
        new PageQuestion(17,1,14100,0,'PH',null,null,null,2,8,3,null,'Environmental Exposures','Environmental Exposures','Environmental Exposures',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(17,2,14200,0,'EN',null,null,null,3,8,3,null,'We ask the next set of questions to learn about the child\'s environment. Please answer as best you can.','We ask the next set of questions to learn about the individual\'s environment. Please answer as best you can.','We ask the next set of questions to learn about the your environment. Please answer as best you can.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(17,3,14220,0,'EN',34,34,34,4,1,1,null,null,'What is the highest level of education that the individual completed?','What is the highest level of education that you have completed?',null,10,10,'edu_level_proband',null,null,null,null,null,'edu_level_proband' ) ,
        new PageQuestion(17,4,14240,0,'EN',34,34,34,4,1,1,null,null,'Is the individual currently employed?','Are you currently employed?',null,29,29,'proband_employed',null,null,null,null,null,'proband_employed' ) ,
        new PageQuestion(17,5,14250,0,'EN',35,35,35,4,4,1,null,null,'Please tell us more about the individual\'s work. Check all that apply.','Please tell us more about your work. Check all that apply.',null,47,47,'proband_employ_details',null,null,null,null,null,'proband_employ_details' ) ,
        new PageQuestion(17,7,14260,0,'EN',36,36,36,4,2,1,null,null,'Please tell us more about why the respondent is not working.','Please tell us more about why you are not working.',null,48,48,'proband_unemploy_details',null,null,null,null,null,'proband_unemploy_details' ) ,
        new PageQuestion(17,9,14270,0,'EN',34,34,34,4,1,1,null,null,'Does the individual currently receive any federal or state benefits, such as Social Security Disability Insurance (SSDI) or Medicaid?','Do you currently receive any federal or state benefits, such as Social Security Disability Insurance (SSDI) or Medicaid?',null,32,32,'proband_govt_benefits',null,null,null,null,null,'proband_govt_benefits' ) 
    ],
    18: [
        new PageQuestion(18,1,14300,0,'EN',null,null,null,3,8,3,null,'This group of questions is about the <strong>mother</strong> of the child.','This group of questions is about the <strong>mother</strong> of the individual.','This group of questions is about your <strong>mother</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(18,2,14400,0,'EN',16,16,16,4,7,1,null,'What was the mother\'s age at the time the child was born?','What was the mother\'s age at the time the individual was born?','What was your mother\'s age at the time you were born?',5,5,5,'mother_age_when_proband_born','Please select',null,null,null,null,'mother_age_when_proband_born' ) ,
        new PageQuestion(18,3,14500,0,'EN',null,null,null,4,1,1,null,'What was the highest grade of school the mother completed or the highest degree received <u>at the time the child was born</u>?','What was the highest grade of school the mother completed or the highest degree received <u>at the time the individual was born</u>?','What was the highest grade of school your mother completed or the highest degree received <u>at the time you were born</u>?',10,10,10,'edu_level_mother',null,null,null,null,null,'edu_level_mother' ) 
    ],
    19: [
        new PageQuestion(19,1,14600,0,'EN',null,null,null,4,7,1,null,'How many weeks pregnant was the mother when the child was born?','How many weeks pregnant was the mother when the individual was born?','How many weeks pregnant was your mother when you were born?',28,28,28,'weeks_pregnant',null,null,null,null,null,'weeks_pregnant' ) ,
        new PageQuestion(19,2,14700,0,'EN',null,null,null,4,1,1,null,'Did the mother breastfeed the child?','Did the mother breastfeed the individual?','Did your mother breastfeed you?',32,32,32,'breastfed',null,null,null,null,null,'breastfed' ) ,
        new PageQuestion(19,3,14800,0,'EN',17,17,17,4,1,1,null,'How long did the mother breastfeed the child?','How long did the mother breastfeed the individual?','How long did your mother breastfeed you?',6,6,6,'breastfed_duration',null,null,null,null,null,'breastfed_duration' ) 
    ],
    20: [
        new PageQuestion(20,1,14900,0,'EN',null,null,null,14,8,3,null,'Answer the next questions based on the <strong>three months before conception, through pregnancy, and through the first year of the child\'s life.</strong>','Answer the next questions based on the <strong>three months before conception, through pregnancy, and through the first year of the individual\'s life</strong>.','Answer the next questions based on the <strong>three months before conception, through pregnancy, and through the first year of your life</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(20,2,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) 
    ],
    21: [
        new PageQuestion(21,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(21,2,15000,0,'EN',null,null,null,4,1,1,null,'Did the <u>mother</u> use tobacco products during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Did the <u>mother</u> use tobacco products during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Did your <u>mother</u> use tobacco products during the three months before conception, through pregnancy, and through the first year of your life?',32,32,32,'tobacco_use_mother',null,null,null,null,null,'tobacco_use_mother' ) ,
        new PageQuestion(21,3,15100,0,'EN',null,null,null,4,1,1,null,'How often was the <u>mother</u> exposed to second-hand smoke during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','How often was the <u>mother</u> exposed to second-hand smoke during the three months before conception, through pregnancy, and through the first year of the individual\'s life.?','How often was your <u>mother</u> exposed to second-hand smoke during the three months before conception, through pregnancy, and through the first year of your life?',14,14,14,'Second_hand_smoke_freq_mother',null,null,null,null,null,'Second_hand_smoke_freq_mother' ) ,
        new PageQuestion(21,4,15200,0,'EN',null,null,null,4,1,1,null,'How often did the mother eat fish, shellfish, or other seafood during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','How often did the mother eat fish, shellfish, or other seafood during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','How often did your mother eat fish, shellfish, or other seafood during the three months before conception, through pregnancy, and through the first year of your life?',14,14,14,'seafood_freq_mother',null,null,null,null,null,'seafood_freq_mother' ) ,
        new PageQuestion(21,5,15300,0,'EN',null,null,null,4,1,1,null,'Excluding prenatal vitmains, did the mother take <u>any</u> prescription medicine during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Excluding prenatal vitamins, did the mother take <u>any</u> prescription medicine during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Excluding prenatal vitamins, did your mother take <u>any</u> prescription medicine during the three months before conception, through pregnancy, and through the first year of your life?',32,32,32,'prescr_drugs_mother',null,null,null,null,null,'prescr_drugs_mother' ) ,
        new PageQuestion(21,6,15400,0,'EN',null,null,null,4,1,1,null,'Excluding prenatal vitamins, did the mother take <u>any</u> over-the-counter medicine during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Excluding prenatal vitamins, did the mother take <u>any</u> over-the-counter medicine during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Excluding prenatal vitamins, did your mother take <u>any</u> over-the-counter medicine during the three months before conception, through pregnancy, and through the first year of your life?',32,32,32,'OTC_drugs_mother',null,null,null,null,null,'OTC_drugs_mother' ) 
    ],
    22: [
        new PageQuestion(22,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(22,2,15500,1,'EN',null,null,null,4,10,3,null,'How often did the mother use the following personal care products during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','How often did the mother use the following personal care products during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','How often did your mother use the following personal care products during the three months before conception, through pregnancy, and through the first year of your life?',14,14,14,null,null,null,null,null,null,null ) 
    ],
    23: [
        new PageQuestion(23,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(23,2,16600,1,'EN',null,null,null,4,4,1,null,'Which of the following best describes the mother\'s occupation during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Which of the following best describes the mother\'s occupation during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Which of the following best describes your mother\'s occupation during the three months before conception, through pregnancy, and through the first year of your life?',20,20,20,'occupation_mother',null,null,null,null,null,'occupation_mother' ) 
    ],
    24: [
        new PageQuestion(24,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(24,2,16800,1,'EN',null,null,null,4,10,3,null,'At work or in daily life, was the mother exposed to any of the following during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','At work or in daily life, was the mother exposed to any of the following during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','At work or in daily life, was your mother exposed to any of the following during the three months before conception, through pregnancy,and through the first year of your life?',30,30,30,null,null,null,null,null,null,null ) 
    ],
    25: [
        new PageQuestion(25,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(25,2,18200,0,'EN',null,null,null,3,8,3,null,'These questions are about the <strong>household</strong> where the child\'s mother lived <strong>during the three months before conception, through pregnancy, and through the first year of the child\'s life.</strong>.','These questions are about the <strong>household</strong> where the individual\'s mother lived <strong>during the three months before conception, through pregnancy, and through the first year of the individual\'s life</strong>.','These questions are about the <strong>household</strong> where your mother lived <strong>during the three months before conception, through pregnancy, and through the first year of your life</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(25,3,18300,0,'EN',null,null,null,4,1,1,null,'How many residences did the mother live in during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','How many residences did the mother live in during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','How many residences did your mother live in during the three months before conception, through pregnancy, and through the first year of your life?',18,18,18,'residence_number_mother',null,null,null,null,null,'residence_number_mother' ) ,
        new PageQuestion(25,4,18400,0,'EN',null,null,null,4,5,1,null,'For any residence where the mother lived during the three months before conception, through pregnancy, and through the first year of the child\'s life., where did the drinking water come from? Select all that apply.','For any residence where the mother lived during the three months before conception, through pregnancy, and through the first year of the individual\'s life, where did the drinking water come from? Select all that apply.','For any residence where your mother lived during the three months before conception, through pregnancy, and through the first year of your life, where did the drinking water come from? Select all that apply.',27,27,27,'water_source_mother',null,null,null,null,null,'water_source_mother' ) ,
        new PageQuestion(25,5,18500,0,'EN',18,18,18,10,6,1,null,'Which city supplied the water?','Which city supplied the water?','Which city supplied the water?',null,null,null,'city_water_source','(Please indicate)',null,null,null,null,'city_water_source' ) ,
        new PageQuestion(25,6,18600,0,'EN',null,null,null,4,1,1,null,'Was any residence where the mother lived during the three months before conception, through pregnancy, and through the first year of the child\'s life. built before 1978?','Was any residence where the mother lived during the three months before conception, through pregnancy, and through the first year of the individual\'s life built before 1978?','Was any residence where your mother lived during the three months before conception, through pregnancy, and through the first year of your life built before 1978?',30,30,30,'residence_pre_78_mother',null,null,null,null,null,'residence_pre_78_mother' ) 
    ],
    26: [
        new PageQuestion(26,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(26,2,18700,1,'EN',null,null,null,4,10,3,null,'Was the mother\'s home treated for insects, bugs, or pests (with foggers <tooltip id="16"/> , fumigators <tooltip id="17"/> , or sprays) by any of the following during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Was the mother\'s home treated for insects, bugs, or pests (with foggers <tooltip id="16"/> , fumigators <tooltip id="17"/> , or sprays) by any of the following during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Was your mother\'s home treated for insects, bugs, or pests (with foggers <tooltip id="16"/> , fumigators <tooltip id="17"/> , or sprays) by any of the following during the three months before conception, through pregnancy, and through the first year of your life?',30,30,30,null,null,null,null,null,null,null ) ,
        new PageQuestion(26,3,19200,1,'EN',null,null,null,4,10,3,null,'If the mother\'s home had a dog, cat, or other mammal, were any of the following used during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','If the mother\'s home had a dog, cat, or other mammal, were any of the following used during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','If your mother\'s home had a dog, cat, or other mammal, were any of the following used during the three months before conception, through pregnancy, and through the first year of your life?',32,32,32,null,null,null,null,null,null,null ) ,
        new PageQuestion(26,4,19600,0,'EN',null,null,null,4,1,1,null,'How often were air fresheners, candles, sprays or similar products used inside the mother\'s home during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','How often were air fresheners, candles, sprays or similar products used inside the mother\'s home during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','How often were air fresheners, candles, sprays or similar products used inside your mother\'s home during the three months before conception, through pregnancy, and through the first year of your life?',15,15,15,'home_fragrance_freq_mother',null,null,null,null,null,'home_fragrance_freq_mother' ) 
    ],
    27: [
        new PageQuestion(27,1,19700,0,'EN',null,null,null,3,8,3,null,'This group of questions is about the <strong>father</strong> of the child.','This group of questions is about the <strong>father</strong> of the individual.','This group of questions is about your<strong>father</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(27,2,19800,0,'EN',null,null,null,4,7,1,null,'What was the father\'s age <u>at the time the child was born</u>?','What was the father\'s age <u>at the time the individual was born</u>?','What was your father\'s age <u>at the time you were born</u>?',5,5,5,'father_age_when_proband_born','Please select',null,null,null,null,'father_age_when_proband_born' ) ,
        new PageQuestion(27,3,19900,0,'EN',null,null,null,4,1,1,null,'What was the highest grade of school the father completed or the highest degree received at the time the child was born?','What was the highest grade of school the father completed or the highest degree received at the time the individual was born?','What was the highest grade of school your father completed or the highest degree received at the time you were born?',10,10,10,'edu_level_father',null,null,null,null,null,'edu_level_father' ) 
    ],
    28: [
        new PageQuestion(28,1,20000,0,'EN',null,null,null,14,8,3,null,'Answer the next questions based on the <strong>three months before conception</strong>.','Answer the next questions based on the <strong>three months before conception</strong>.','Answer the next questions based on the <strong>three months before conception</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(28,2,20050,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>',null,null,null,null,null,null,null,null,null,null ) 
    ],
    29: [
        new PageQuestion(29,1,20050,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(29,2,20100,0,'EN',null,null,null,4,1,1,null,'Did the <u>father</u> use tobacco products during the three months before conception?','Did the <u>father</u> use tobacco products during the three months before conception?','Did your <u>father</u> use tobacco products during the three months before conception?',32,32,32,'tobacco_use_father',null,null,null,null,null,'tobacco_use_father' ) ,
        new PageQuestion(29,3,20200,0,'EN',null,null,null,4,1,1,null,'How often was the <u>father</u> exposed to second-hand smoke during the three months before conception?','How often was the <u>father</u> exposed to second-hand smoke during the three months before conception?','How often was your <u>father</u> exposed to second-hand smoke during the three months before conception?',14,14,14,'Second_hand_smoke_freq_father',null,null,null,null,null,'Second_hand_smoke_freq_father' ) ,
        new PageQuestion(29,4,20300,0,'EN',null,null,null,4,1,1,null,'How often did the father eat fish, shellfish, or other seafood during the three months before conception?','How often did the father eat fish, shellfish, or other seafood during the three months before conception?','How often did your father eat fish, shellfish, or other seafood during the three months before conception?',14,14,14,'seafood_freq_father',null,null,null,null,null,'seafood_freq_father' ) ,
        new PageQuestion(29,5,20400,0,'EN',null,null,null,4,1,1,null,'Did the father take any prescription medicine during the three months before conception?','Did the father take any prescription medicine during the three months before conception?','Did your father take any prescription medicine during the three months before conception?',32,32,32,'prescr_drugs_father',null,null,null,null,null,'prescr_drugs_father' ) ,
        new PageQuestion(29,6,20500,0,'EN',null,null,null,4,1,1,null,'Did the father take any over-the-counter medicine during the three months before conception?','Did the father take any over-the-counter medicine during the three months before conception?','Did your father take any over-the-counter medicine during the three months before conception?',32,32,32,'OTC_drugs_father',null,null,null,null,null,'OTC_drugs_father' ) 
    ],
    30: [
        new PageQuestion(30,1,20050,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>','<Placeholder for the URL of timeline 2>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(30,2,20600,1,'EN',null,null,null,4,10,3,null,'How often did the father use the following personal care products during the three months before conception?','How often did the father use the following personal care products during the three months before conception?','How often did your father use the following personal care products during the three months before conception?',14,14,14,null,null,null,null,null,null,null ) 
    ],
    31: [
        new PageQuestion(31,1,21700,0,'EN',null,null,null,14,8,3,null,'Answer the next questions <strong>based on the three months before conception, through pregnancy, and through the first year of the child\'s life.</strong>.','Answer the next questions <strong>based on the three months before conception, through pregnancy, and through the first year of the individual\'s life</strong>.','Answer the next questions <strong>based on the three months before conception, through pregnancy, and through the first year of your life</strong>.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(31,2,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) 
    ],
    32: [
        new PageQuestion(32,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(32,2,21800,1,'EN',null,null,null,4,4,3,null,'Which of the following best describes the father\'s occupation during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','Which of the following best describes the father\'s occupation during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','Which of the following best describes your father\'s occupation during the three months before conception, through pregnancy, and through the first year of your life?',20,20,20,'occupation_father',null,null,null,null,null,'occupation_father' ) 
    ],
    33: [
        new PageQuestion(33,1,14950,0,'EN',null,null,null,17,8,3,null,'<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>','<Placeholder for the URL of timeline 1>',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(33,2,22000,1,'EN',null,null,null,4,10,3,null,'At work or in daily life, was the father exposed to any of the following during the three months before conception, through pregnancy, and through the first year of the child\'s life.?','At work or in daily life, was the father exposed to any of the following during the three months before conception, through pregnancy, and through the first year of the individual\'s life?','At work or in daily life, was your father exposed to any of the following during the three months before conception, through pregnancy, and through the first year of your life?',30,30,30,null,null,null,null,null,null,null ) 
    ],
    34: [
        new PageQuestion(34,1,23400,0,'EN',null,null,null,3,8,3,null,'The following question is about the child and covers the first year of their life.','The following question is about the individual and covers the first year of their life.','The following question is about you and covers the first year of your life.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(34,2,23500,0,'EN',null,null,null,4,1,1,null,'How often was the child exposed to second-hand smoke <u>during the first year of their life</u>.','How often was the individual exposed to second-hand smoke <u>during the first year of their life</u>.','How often were you exposed to second-hand smoke <u>during the first year of your life</u>.',14,14,14,'Second_hand_smoke_freq_child',null,null,null,null,null,'Second_hand_smoke_freq_child' ) 
    ],
    35: [
        new PageQuestion(35,1,23600,0,'SB',null,null,null,2,8,3,null,'Sibling Information','Sibling Information','Sibling Information',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(35,2,23700,0,'SB',null,null,null,3,8,3,null,'We ask questions about the child\'s siblings to know if others in your family have ASD.','We ask questions about the individual\'s siblings to know if others in their family have ASD.','We ask questions about your siblings to know if others in your family have ASD.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(35,3,23800,0,'SB',null,null,null,4,7,1,null,'How many siblings does the child have?','How many siblings does the individual have?','How many siblings do you have?',45,45,45,'nb_sibling',null,null,null,null,null,'has_sibling' ) ,
        new PageQuestion(35,4,23900,0,'SB',19,19,19,4,1,1,null,'How many of the child\'s siblings have received a diagnosis of ASD, which includes Asperger syndrome, childhood disintegrative disorder, and pervasive developmental disorder not otherwise specified (PDD-NOS)?','How many of the individual\'s siblings have received a diagnosis of ASD, which includes Asperger syndrome, individualhood disintegrative disorder, and pervasive developmental disorder not otherwise specified (PDD-NOS)?','How many of your siblings have received a diagnosis of ASD, which includes Asperger syndrome, individualhood disintegrative disorder, and pervasive developmental disorder not otherwise specified (PDD-NOS)?',45,45,45,'nb_sibling_with_ASD',null,null,null,null,null,'nb_sibling_with_ASD' ) 
    ],
    36: [
        new PageQuestion(36,1,24100,0,'RC',null,null,null,2,8,3,null,'Recontact','Recontact','Recontact',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(36,2,24200,0,'RC',null,null,null,3,8,3,null,'As we learn more about ASD, we may develop other studies that interest you. If you are willing to let us contact you about these new studies, please enter your information below. We will not share your contact information with other people. ','As we learn more about ASD, we may develop other studies that interest you. If you are willing to let us contact you about these new studies, please enter your information below. We will not share your contact information with other people. ','As we learn more about ASD, we may develop other studies that interest you. If you are willing to let us contact you about these new studies, please enter your information below. We will not share your contact information with other people. ',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(36,3,24300,0,'RC',null,null,null,4,1,2,null,'Please select one of the following:','Please select one of the following:','Please select one of the following:',22,22,22,'recontact',null,null,null,null,null,'recontact' ) ,
        new PageQuestion(36,4,24400,0,'RC',20,20,20,7,6,2,null,'Full Name','Full Name','Full Name',null,null,null,'recontact_full_name',null,null,null,null,'Please provide a complete name that does not start with a space character.','recontact_full_name' ) ,
        new PageQuestion(36,5,24500,0,'RC',20,20,20,4,8,3,null,'<u>Please provide as many phone numbers as possible</u> so that we can easily reach you.','<u>Please provide as many phone numbers as possible</u> so that we can easily reach you.','<u>Please provide as many phone numbers as possible</u> so that we can easily reach you.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(36,6,24600,0,'RC',20,20,20,7,6,2,null,'Main phone number','Main phone number','Main phone number',null,null,null,'phone_main_number',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->','phone_main_number' ) ,
        new PageQuestion(36,7,24700,0,'RC',21,21,21,7,6,0,null,'ext.','ext.','ext.',null,null,null,'phone_main_ext',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,8,24800,0,'RC',22,22,22,13,3,0,null,'The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.',29,29,29,'phone_main_foreign',null,null,null,null,null,null ) ,
        new PageQuestion(36,9,24900,0,'RC',20,20,20,7,6,0,null,'Alt phone number 1','Alt phone number 1','Alt phone number 1',null,null,null,'phone_alt1_number',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,10,25000,0,'RC',23,23,23,7,6,0,null,'ext.','ext.','ext.',null,null,null,'phone_alt1_ext',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,11,25100,0,'RC',24,24,24,13,3,0,null,'The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.',29,29,29,'phone_alt1_foreign',null,null,null,null,null,null ) ,
        new PageQuestion(36,12,25200,0,'RC',25,25,25,7,6,0,null,'Alt phone number 2','Alt phone number 2','Alt phone number 2',null,null,null,'phone_alt2_number',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,13,25300,0,'RC',26,26,26,7,6,0,null,'ext.','ext.','ext.',null,null,null,'phone_alt2_ext',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,14,25400,0,'RC',27,27,27,13,3,0,null,'The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.',29,29,29,'phone_alt2_foreign',null,null,null,null,null,null ) ,
        new PageQuestion(36,15,25500,0,'RC',28,28,28,7,6,0,null,'Alt phone number 3','Alt phone number 3','Alt phone number 3',null,null,null,'phone_alt3_number',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,16,25600,0,'RC',29,29,29,7,6,0,null,'ext.','ext.','ext.',null,null,null,'phone_alt3_ext',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,17,25700,0,'RC',30,30,30,13,3,0,null,'The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.',29,29,29,'phone_alt3_foreign',null,null,null,null,null,null ) ,
        new PageQuestion(36,18,25800,0,'RC',31,31,31,7,6,0,null,'Alt phone number 4','Alt phone number 4','Alt phone number 4',null,null,null,'phone_alt4_number',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,19,25900,0,'RC',32,32,32,7,6,0,null,'ext.','ext.','ext.',null,null,null,'phone_alt4_ext',null,null,null,null,'<!-- Handled by the validation_rule  function. See CR #98 -->',null ) ,
        new PageQuestion(36,20,26000,0,'RC',33,33,33,13,3,0,null,'The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.','The above phone number does not have 10 digits. Please enter a 10-digit phone number or check this box if this is a foreign number.',29,29,29,'phone_alt4_foreign',null,null,null,null,null,null ) ,
        new PageQuestion(36,21,26100,0,'RC',20,20,20,7,6,1,null,'Email address','Email address','Email address',null,null,null,'recontact_email',null,null,null,null,'Please enter a valid email address.','recontact_email' ) 
    ],
    37: [
        new PageQuestion(37,1,26200,0,'TY',null,null,null,2,8,3,null,'Your information has been submitted!','Your information has been submitted!','Your information has been submitted!',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(37,2,26300,0,'TY',null,null,null,12,8,3,null,'"Thank you for your participation in the NCAP survey.  We truly value the information you have provided.  Your responses are very important to better understand probable links between the exposure to environmental and social factors and ASD in the United States.<br><br>','Thank you for your participation in the NCAP survey.  We truly value the information you have provided.  Your responses are very important to better understand probable links between the exposure to environmental and social factors and ASD in the United States.<br><br>\nIf you wish to fill out the information for another individual, please click the \u201cReturn to main page\u201d button below and then click \\"Start the survey\\" link on the main page to start another survey. Otherwise, click on \\"Exit survey\\".','Thank you for your participation in the NCAP survey.  We truly value the information you have provided.  Your responses are very important to better understand probable links between the exposure to environmental and social factors and ASD in the United States.<br><br>\nIf you wish to fill out the information for another individual, please click the \u201cReturn to main page\u201d button below and then click \\"Start the survey\\" link on the main page to start another survey. Otherwise, click on \\"Exit survey\\".',null,null,null,null,null,null,null,null,null,null ) 
    ],
    38: [
        new PageQuestion(38,1,420,0,'PH',null,null,null,14,8,3,null,'When taking this survey, if you wish to go to the next web page or the previous web page, please use the navigation buttons (\'Next\' and \'Back\') at the bottom of each web page.  Please do not use your browser\'s default navigation buttons.','When taking this survey, if you wish to go to the next web page or the previous web page, please use the navigation buttons (\'Next\' and \'Back\') at the bottom of each web page.  Please do not use your browser\'s default navigation buttons.','When taking this survey, if you wish to go to the next web page or the previous web page, please use the navigation buttons (\'Next\' and \'Back\') at the bottom of each web page.  Please do not use your browser\'s default navigation buttons.',null,null,null,null,null,null,null,null,null,null ) ,
        new PageQuestion(38,2,460,0,'PH',null,null,null,14,8,3,null,'If you wish to exit the survey before completing it, we strongly recommend that you click on the \'Exit Survey\' button.  This will ensure that the information you provided is erased from this device\'s memory and therefore not available to other users of this device.','If you wish to exit the survey before completing it, we strongly recommend that you click on the \'Exit Survey\' button.  This will ensure that the information you provided is erased from this device\'s memory and therefore not available to other users of this device.','If you wish to exit the survey before completing it, we strongly recommend that you click on the \'Exit Survey\' button.  This will ensure that the information you provided is erased from this device\'s memory and therefore not available to other users of this device.',null,null,null,null,null,null,null,null,null,null ) 
    ]
};
